/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import CONTROLLER.ChiTietHoaDonDAO;
import CONTROLLER.HoaDonDAO;
import CONTROLLER.updateDAO;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.Cell;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ChiTietHoaDon;
import model.HoaDon;
import model.MatHang;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.ss.usermodel.HorizontalAlignment;
import org.apache.poi.ss.usermodel.VerticalAlignment;
import org.apache.poi.ss.util.CellUtil;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;



/**
 *
 * @author The Phong
 */
public class HoaDon_form extends javax.swing.JFrame {

    private ArrayList<HoaDon> list;
    DefaultTableModel model;
    private ArrayList<ChiTietHoaDon> list1;
    DefaultTableModel model1;
    /**
     * Creates new form frmTrangChu
     */
    public HoaDon_form() {
        initComponents();
        //ShowTable();
        FillComboNV();
        FillComboCT();
        FillComboKH();
        //ShowTableCTHD();
        FillComboMaHD_CTHD();
        FillComboMaMH_CTHD();
        this.setLocationRelativeTo(null);
        list = new HoaDonDAO().getListHoadon();
        list1= new ChiTietHoaDonDAO().getlistChiTietHoaDon();
        model = (DefaultTableModel) tblHoaDon_HoaDon.getModel();
        model.setColumnIdentifiers(new Object[]{
            "STT", "MaHoaDon", "MaNV", "MaCT", "MaKH", "NgayLapHD", "GhiChu"
        });
        model1 =(DefaultTableModel) tblCTHoaDon_ChiTietHoaDon.getModel();
        model1.setColumnIdentifiers(new Object[]{
            "STT", "MaHoaDon", "MaMatHang", "SoLuong", "ThanhTien", "DonGia", "TienGiamGia"
        });
        
        clearTable();
        showTable();// hien thi thong tin trong danh sach
        clearTableCTHD();
        //showTableCTHD();
    }
    
     public void showTable() {
        int i=1;
        for (HoaDon s : list) {
            model.addRow(new Object[]{
                i++, s.getMaHoaDon(), s.getMaNV(), s.getMaChuongTrinh(), s.getMaKH(), s.getNgayLapHD(), s.getGhiChu()
            });
        }
     }
      public void showTableCTHD() {
        int i=1;
        for (ChiTietHoaDon s : list1) {
            model1.addRow(new Object[]{
                i++, s.getMaHoaDon(), s.getMaMatHang(), s.getSoluong(), s.getThanhTien(), s.getDonGia(), s.getTienGiamGia()
            });
        }
     }
   public void clearTable() {
    for( int i = model.getRowCount() - 1; i >= 0; i-- ) {
        model.removeRow(i);
    }
   }
   public void clearTableCTHD() {
    for( int i = model1.getRowCount() - 1; i >= 0; i-- ) {
        model1.removeRow(i);
    }
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateNgayLapHD1 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        tblHoaDon_HoaDon = new javax.swing.JTable();
        jScrollPane15 = new javax.swing.JScrollPane();
        tblCTHoaDon_ChiTietHoaDon = new javax.swing.JTable();
        jLabel34 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        lblMaHoaDon_HoaDon = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane16 = new javax.swing.JScrollPane();
        txGhiChu = new javax.swing.JTextArea();
        btnThem_HoaDon = new javax.swing.JButton();
        btnXoa_HoaDon = new javax.swing.JButton();
        btnSua_HoaDon = new javax.swing.JButton();
        lblNgayLap = new javax.swing.JLabel();
        txMaHoaDon = new javax.swing.JTextField();
        lblTongTien_HoaDon = new javax.swing.JLabel();
        boxMaNV = new javax.swing.JComboBox<>();
        boxMaChuongTrinh = new javax.swing.JComboBox<>();
        boxMaKhachHang = new javax.swing.JComboBox<>();
        dateNgayLapHD = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        date1NgayLapHD = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        date2NgayLapHD = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        lblSoLuong_CTPM = new javax.swing.JLabel();
        lblMaHoaDon = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        boxMaHoaDon_CTHD = new javax.swing.JComboBox<>();
        btnThem_ChiTietHoaDon = new javax.swing.JButton();
        btnSua_ChiTietHoaDon = new javax.swing.JButton();
        btnXuat = new javax.swing.JButton();
        jLabel57 = new javax.swing.JLabel();
        txSoLuong = new javax.swing.JTextField();
        lblMaHoaDon1 = new javax.swing.JLabel();
        boxMaMatHang_CTHD = new javax.swing.JComboBox<>();
        txThanhTien = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        txTienGiamGia = new javax.swing.JTextField();
        txDonGia = new javax.swing.JTextField();
        btnReset_ChiTietHoaDon1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hóa Đơn");

        dateNgayLapHD1.setBackground(new java.awt.Color(204, 204, 255));
        dateNgayLapHD1.setPreferredSize(new java.awt.Dimension(1176, 581));
        dateNgayLapHD1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                dateNgayLapHD1ComponentShown(evt);
            }
        });

        tblHoaDon_HoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã Hóa Đơn", "Mã Nhân Viên", "Mã Chương Trình", "Ngày Lập HĐ", "Mã Khách Hàng", "Ghi Chú"
            }
        ));
        tblHoaDon_HoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDon_HoaDonMouseClicked(evt);
            }
        });
        tblHoaDon_HoaDon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblHoaDon_HoaDonKeyReleased(evt);
            }
        });
        jScrollPane10.setViewportView(tblHoaDon_HoaDon);

        tblCTHoaDon_ChiTietHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Hóa Đơn", "Mã Mặt Hàng", "Số Lượng", "Thành Tiền", "Đơn Giá", "Tiền Giảm Giá"
            }
        ));
        tblCTHoaDon_ChiTietHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCTHoaDon_ChiTietHoaDonMouseClicked(evt);
            }
        });
        jScrollPane15.setViewportView(tblCTHoaDon_ChiTietHoaDon);

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(51, 102, 255));
        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaige/chitiet.png"))); // NOI18N
        jLabel34.setText("Bảng Chi Tiết Hóa Đơn");

        jPanel14.setBackground(new java.awt.Color(204, 204, 255));
        jPanel14.setPreferredSize(new java.awt.Dimension(400, 227));

        jLabel33.setText("Ghi Chú");

        lblMaHoaDon_HoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaige/key.png"))); // NOI18N
        lblMaHoaDon_HoaDon.setText("Mã Hóa Đơn");

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaige/key1.png"))); // NOI18N
        jLabel31.setText("Mã Nhân Viên");

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaige/key2.png"))); // NOI18N
        jLabel30.setText("Mã Chương Trình");
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
        });

        txGhiChu.setColumns(20);
        txGhiChu.setRows(5);
        jScrollPane16.setViewportView(txGhiChu);

        btnThem_HoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaige/Thêm.png"))); // NOI18N
        btnThem_HoaDon.setText("Thêm ");
        btnThem_HoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem_HoaDonActionPerformed(evt);
            }
        });

        btnXoa_HoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaige/1111.png"))); // NOI18N
        btnXoa_HoaDon.setText("Xóa");
        btnXoa_HoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa_HoaDonActionPerformed(evt);
            }
        });

        btnSua_HoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaige/update.png"))); // NOI18N
        btnSua_HoaDon.setText("Sửa");
        btnSua_HoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua_HoaDonActionPerformed(evt);
            }
        });

        lblNgayLap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaige/date1.png"))); // NOI18N
        lblNgayLap.setText("Ngày Lập HĐ");
        lblNgayLap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNgayLapMouseClicked(evt);
            }
        });

        lblTongTien_HoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaige/secrecy-icon.png"))); // NOI18N
        lblTongTien_HoaDon.setText("Mã Khách Hàng");

        boxMaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxMaNVActionPerformed(evt);
            }
        });

        boxMaChuongTrinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxMaChuongTrinhActionPerformed(evt);
            }
        });

        boxMaKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxMaKhachHangActionPerformed(evt);
            }
        });

        dateNgayLapHD.setDateFormatString("dd-MM-yyyy");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaige/refresh.png"))); // NOI18N
        jButton1.setText("Cập Nhật");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaige/icons8-google-web-search-24.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        date1NgayLapHD.setDateFormatString("dd/MM/yyyy");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("OR");

        date2NgayLapHD.setDateFormatString("dd/MM/yyyy");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaige/quanlyyy.png"))); // NOI18N
        jLabel5.setText(" Bảng điều khiển");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblTongTien_HoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMaHoaDon_HoaDon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boxMaChuongTrinh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boxMaNV, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txMaHoaDon)
                            .addComponent(boxMaKhachHang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThem_HoaDon)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoa_HoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSua_HoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNgayLap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addComponent(date1NgayLapHD, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(date2NgayLapHD, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(dateNgayLapHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1)
                                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMaHoaDon_HoaDon)
                    .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel33)))
                .addGap(0, 0, 0)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boxMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31))
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(boxMaChuongTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTongTien_HoaDon)
                            .addComponent(boxMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNgayLap)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dateNgayLapHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(date1NgayLapHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(date2NgayLapHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem_HoaDon)
                            .addComponent(btnXoa_HoaDon)
                            .addComponent(btnSua_HoaDon)
                            .addComponent(jButton1))
                        .addContainerGap())))
        );

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(51, 102, 255));
        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaige/hoadon.png"))); // NOI18N
        jLabel35.setText("Bảng Hóa Đơn");

        jPanel19.setBackground(new java.awt.Color(204, 204, 255));
        jPanel19.setPreferredSize(new java.awt.Dimension(400, 230));

        lblSoLuong_CTPM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaige/money.png"))); // NOI18N
        lblSoLuong_CTPM.setText("Thành Tiền");

        lblMaHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaige/key2.png"))); // NOI18N
        lblMaHoaDon.setText("Mã Mặt Hàng");

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaige/amount.png"))); // NOI18N
        jLabel40.setText("Số lượng");

        boxMaHoaDon_CTHD.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                boxMaHoaDon_CTHDItemStateChanged(evt);
            }
        });

        btnThem_ChiTietHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaige/Thêm.png"))); // NOI18N
        btnThem_ChiTietHoaDon.setText("Thêm");
        btnThem_ChiTietHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem_ChiTietHoaDonActionPerformed(evt);
            }
        });

        btnSua_ChiTietHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaige/update.png"))); // NOI18N
        btnSua_ChiTietHoaDon.setText("Sửa");
        btnSua_ChiTietHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua_ChiTietHoaDonActionPerformed(evt);
            }
        });

        btnXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaige/exel.png"))); // NOI18N
        btnXuat.setText("Xuất");
        btnXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatActionPerformed(evt);
            }
        });

        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaige/gianhap.png"))); // NOI18N
        jLabel57.setText("Đơn Giá");

        txSoLuong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txSoLuongKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txSoLuongKeyReleased(evt);
            }
        });

        lblMaHoaDon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaige/key.png"))); // NOI18N
        lblMaHoaDon1.setText("Mã Hóa Đơn");

        boxMaMatHang_CTHD.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                boxMaMatHang_CTHDItemStateChanged(evt);
            }
        });
        boxMaMatHang_CTHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxMaMatHang_CTHDActionPerformed(evt);
            }
        });

        txThanhTien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txThanhTienKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txThanhTienKeyReleased(evt);
            }
        });

        jLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaige/sale.png"))); // NOI18N
        jLabel58.setText("Tiền Giảm Giá");

        txTienGiamGia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txTienGiamGiaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txTienGiamGiaKeyReleased(evt);
            }
        });

        txDonGia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txDonGiaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txDonGiaKeyReleased(evt);
            }
        });

        btnReset_ChiTietHoaDon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaige/refresh.png"))); // NOI18N
        btnReset_ChiTietHoaDon1.setText("Cập Nhật");
        btnReset_ChiTietHoaDon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReset_ChiTietHoaDon1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaige/quanlyyy.png"))); // NOI18N
        jLabel6.setText(" Bảng điều khiển");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(btnThem_ChiTietHoaDon)
                        .addGap(18, 18, 18)
                        .addComponent(btnSua_ChiTietHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblMaHoaDon1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblMaHoaDon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel40, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel57, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel58, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                        .addComponent(lblSoLuong_CTPM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txThanhTien, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txSoLuong, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(boxMaMatHang_CTHD, javax.swing.GroupLayout.Alignment.LEADING, 0, 154, Short.MAX_VALUE)
                        .addComponent(boxMaHoaDon_CTHD, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txTienGiamGia, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txDonGia, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnReset_ChiTietHoaDon1)
                        .addGap(42, 42, 42)
                        .addComponent(btnXuat)))
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaHoaDon1)
                    .addComponent(boxMaHoaDon_CTHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaHoaDon)
                    .addComponent(boxMaMatHang_CTHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(txSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSoLuong_CTPM)
                    .addComponent(txThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel57)
                    .addComponent(txDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txTienGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel58))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem_ChiTietHoaDon)
                            .addComponent(btnSua_ChiTietHoaDon)
                            .addComponent(btnReset_ChiTietHoaDon1)
                            .addComponent(btnXuat))))
                .addContainerGap())
        );

        javax.swing.GroupLayout dateNgayLapHD1Layout = new javax.swing.GroupLayout(dateNgayLapHD1);
        dateNgayLapHD1.setLayout(dateNgayLapHD1Layout);
        dateNgayLapHD1Layout.setHorizontalGroup(
            dateNgayLapHD1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dateNgayLapHD1Layout.createSequentialGroup()
                .addGroup(dateNgayLapHD1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dateNgayLapHD1Layout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addGap(268, 268, 268))
                    .addGroup(dateNgayLapHD1Layout.createSequentialGroup()
                        .addGroup(dateNgayLapHD1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(dateNgayLapHD1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(dateNgayLapHD1Layout.createSequentialGroup()
                                    .addGap(44, 44, 44)
                                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(dateNgayLapHD1Layout.createSequentialGroup()
                                    .addGap(314, 314, 314)
                                    .addComponent(jLabel35))))
                        .addGap(30, 30, 30)))
                .addGroup(dateNgayLapHD1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE))
                .addContainerGap())
        );
        dateNgayLapHD1Layout.setVerticalGroup(
            dateNgayLapHD1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dateNgayLapHD1Layout.createSequentialGroup()
                .addGroup(dateNgayLapHD1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dateNgayLapHD1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel35)
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 38, Short.MAX_VALUE))
                    .addGroup(dateNgayLapHD1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                        .addGap(6, 6, 6)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dateNgayLapHD1, javax.swing.GroupLayout.DEFAULT_SIZE, 1216, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dateNgayLapHD1, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblCTHoaDon_ChiTietHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCTHoaDon_ChiTietHoaDonMouseClicked
        showDB1();
    }//GEN-LAST:event_tblCTHoaDon_ChiTietHoaDonMouseClicked

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked

    }//GEN-LAST:event_jLabel30MouseClicked

    private void btnThem_HoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem_HoaDonActionPerformed
        HoaDon s = new HoaDon();
        SimpleDateFormat sdf=new  SimpleDateFormat("yyyy-MM-dd"); 
        String date=sdf.format(dateNgayLapHD.getDate());
        s.setMaHoaDon(txMaHoaDon.getText());
        s.setMaNV(boxMaNV.getSelectedItem().toString());
        s.setMaChuongTrinh(boxMaChuongTrinh.getSelectedItem().toString());
        s.setMaKH(boxMaKhachHang.getSelectedItem().toString());
        s.setNgayLapHD(date);
        s.setGhiChu(txGhiChu.getText());  
        if(new HoaDonDAO().addHoadon(s)){
            JOptionPane.showMessageDialog(null, "Add Success!");
            list.add(s); // them vao danh sach SV
        } else{
            JOptionPane.showMessageDialog(null, "Add Faild!");
        }
        clearTable();
        list = new HoaDonDAO().getListHoadon();
        showTable();
    }//GEN-LAST:event_btnThem_HoaDonActionPerformed

    private void btnXoa_HoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa_HoaDonActionPerformed
        HoaDon s = new HoaDon();
        s.setMaHoaDon(txMaHoaDon.getText());
        if(new HoaDonDAO().xoaHoadon(s)){
            JOptionPane.showMessageDialog(null, "Delete Success!");
            list.add(s); // them vao danh sach SV
        } else{
            JOptionPane.showMessageDialog(null, "Delete Faild!");
        }
        clearTable();
        list = new HoaDonDAO().getListHoadon();
        showTable();
    }//GEN-LAST:event_btnXoa_HoaDonActionPerformed

    private void btnSua_HoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua_HoaDonActionPerformed
        HoaDon s = new HoaDon();
        SimpleDateFormat sdf=new  SimpleDateFormat("yyyy-MM-dd"); 
        String date=sdf.format(dateNgayLapHD.getDate());
        s.setMaHoaDon(txMaHoaDon.getText());
        s.setMaNV(boxMaNV.getSelectedItem().toString());
        s.setMaChuongTrinh(boxMaChuongTrinh.getSelectedItem().toString());
        s.setMaKH(boxMaKhachHang.getSelectedItem().toString());
        s.setNgayLapHD(date);
        s.setGhiChu(txGhiChu.getText());  
        if(new HoaDonDAO().fixHoadon(s)){
            JOptionPane.showMessageDialog(null, "Fix Success!");
            list.add(s); // them vao danh sach SV
        } else{
            JOptionPane.showMessageDialog(null, "Fix Faild!");
        }
        clearTable();
        list = new HoaDonDAO().getListHoadon();
        showTable();
    }//GEN-LAST:event_btnSua_HoaDonActionPerformed

    public void FillComboNV(){
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/banhang","root","");
            String sql = "SELECT * FROM nhanvien";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                    String MaNV=rs.getString("MaNV");
                    boxMaNV.addItem(MaNV);
            } 
        } 
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    public void FillComboCT(){
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/banhang","root","");
            String sql = "SELECT * FROM `chuongtrinhkhuyenmai`";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                    String MaCT=rs.getString("MaChuongTrinh");
                    boxMaChuongTrinh.addItem(MaCT);
            } 
        } 
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    public void FillComboKH(){
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/banhang","root","");
            String sql = "SELECT * FROM khachhang";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                    String MaKH=rs.getString("MaKH");
                    boxMaKhachHang.addItem(MaKH);
            } 
        } 
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    public void FillComboMaHD_CTHD(){
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/banhang","root","");
            /*String sql = "SELECT * \n" +
"FROM hoadon\n" +
"WHERE NOT EXISTS (SELECT *\n" +
"                  FROM chitiethoadon\n" +
"                  WHERE chitiethoadon.MaHoaDon=hoadon.MaHoaDon)";*/
            String sql= "Select *from hoadon";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                    String MaHD=rs.getString("MaHoaDon");
                    boxMaHoaDon_CTHD.addItem(MaHD);
            } 
        } 
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    public void FillComboMaMH_CTHD(){
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/banhang","root","");
            String sql = "SELECT * FROM mathang";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                    String MaMH=rs.getString("MaMatHang");
                    boxMaMatHang_CTHD.addItem(MaMH);
            } 
        } 
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    private void lblNgayLapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNgayLapMouseClicked

    }//GEN-LAST:event_lblNgayLapMouseClicked

    private void dateNgayLapHD1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_dateNgayLapHD1ComponentShown
       
    }//GEN-LAST:event_dateNgayLapHD1ComponentShown

    private void tblHoaDon_HoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDon_HoaDonMouseClicked
        showDB();
        showDBbb();
    }//GEN-LAST:event_tblHoaDon_HoaDonMouseClicked
    public void showDBbb(){
        int selectrow=tblHoaDon_HoaDon.getSelectedRow();
        Object[] row= new Object[7];
        String ss=tblHoaDon_HoaDon.getValueAt(selectrow,1).toString();
        clearTableCTHD();
        System.out.println(ss);
        for (int i=0;i<list1.size();i++){
            if (list1.get(i).getMaHoaDon().equals(ss)){
                int k=0;
                k++;
                row[0]=k;
                row[1]=list1.get(i).getMaHoaDon();
                row[2]=list1.get(i).getMaMatHang();
                row[3]=list1.get(i).getSoluong();
                row[4]=list1.get(i).getThanhTien();
                row[5]=list1.get(i).getDonGia();
                row[6]=list1.get(i).getTienGiamGia();
                model1.addRow(row);
            }
        }
    }
    private void boxMaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxMaNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxMaNVActionPerformed

    private void boxMaChuongTrinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxMaChuongTrinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxMaChuongTrinhActionPerformed

    private void boxMaKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxMaKhachHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxMaKhachHangActionPerformed

    private void txThanhTienKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txThanhTienKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txThanhTienKeyReleased

    private void txThanhTienKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txThanhTienKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txThanhTienKeyPressed

    private void boxMaMatHang_CTHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxMaMatHang_CTHDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxMaMatHang_CTHDActionPerformed

    private void boxMaMatHang_CTHDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_boxMaMatHang_CTHDItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_boxMaMatHang_CTHDItemStateChanged

    private void txSoLuongKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txSoLuongKeyReleased

    }//GEN-LAST:event_txSoLuongKeyReleased

    private void txSoLuongKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txSoLuongKeyPressed

    }//GEN-LAST:event_txSoLuongKeyPressed
    
    private void btnXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatActionPerformed
        
        FileOutputStream out = null;
        try {
            XSSFWorkbook workbook = new XSSFWorkbook();
            XSSFSheet spreadsheet = workbook.createSheet("ChiTietHoaDon");
            XSSFRow row = null;
            XSSFCell cell = null;
            int width = 15; // Where width is number of caracters 
            spreadsheet.setDefaultColumnWidth(width);
           /* CellStyle cellStyle = workbook.createCellStyle();
            cellStyle.setVerticalAlignment(VerticalAlignment.CENTER);
            cellStyle.setAlignment(HorizontalAlignment.LEFT);
            cell.setCellStyle(cellStyle);*/
            row = spreadsheet.createRow((short) 2);// hàng 2
            row.setHeight((short) 300);// độ rộng của hàng
            cell = row.createCell(3, CellType.STRING);// vị trí của cột // cột 3 hàng 2
            cell.setCellValue("CHI TIẾT HÓA ĐƠN");
            
            row = spreadsheet.createRow((short) 3); // cột 3
            cell = row.createCell(0, CellType.STRING);
            cell.setCellValue("STT");
            cell = row.createCell(1, CellType.STRING);
            cell.setCellValue("Mã Hóa Đơn");
            cell = row.createCell(2, CellType.STRING);
            cell.setCellValue("Mã Mặt Hàng");
            cell = row.createCell(3, CellType.STRING);
            cell.setCellValue("Số Lượng");
            cell = row.createCell(4, CellType.STRING);
            cell.setCellValue("Thành Tiền");
            cell = row.createCell(5, CellType.STRING);
            cell.setCellValue("Đơn giá");
            cell = row.createCell(6, CellType.STRING);
            cell.setCellValue("Tiền Giảm Giá");
            for (int i = 0; i < list1.size(); i++) {  
                row = spreadsheet.createRow((short) 4 + i);
                row.setHeight((short) 300);
                row.createCell(0).setCellValue(i + 1);
                row.createCell(1).setCellValue(list1.get(i).getMaHoaDon());
                row.createCell(2).setCellValue(list1.get(i).getMaMatHang());
                row.createCell(3).setCellValue(list1.get(i).getSoluong());
                row.createCell(4).setCellValue(list1.get(i).getThanhTien());
                row.createCell(5).setCellValue(list1.get(i).getDonGia());
                row.createCell(6).setCellValue(list1.get(i).getTienGiamGia());
            }
            out = new FileOutputStream(new File("E:/chitiethoadon.xlsx"));
             workbook.write(out);
            out.close();
           JOptionPane.showMessageDialog(null,"Xuat thanh cong");
        } catch (Exception ex) {
           ex.printStackTrace();
        } 
    }//GEN-LAST:event_btnXuatActionPerformed

    private void btnSua_ChiTietHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua_ChiTietHoaDonActionPerformed
             ChiTietHoaDon s=new ChiTietHoaDon();
            boolean k=false;
            try {
                s.setMaHoaDon(boxMaHoaDon_CTHD.getSelectedItem().toString());
                s.setMaMatHang(boxMaMatHang_CTHD.getSelectedItem().toString());
                s.setSoluong(txSoLuong.getText());
                s.setThanhTien(Integer.parseInt(txThanhTien.getText()));
                s.setDonGia(Integer.parseInt(txDonGia.getText()));
                Object[] row= new Object[7];
                s.setTienGiamGia(Integer.parseInt(txTienGiamGia.getText()));
                /*for (int i=0;i<list1.size();i++)
                    if (boxMaHoaDon_CTHD.getSelectedItem().toString())
                            if (list1.get(i).getMaHoaDon().equals(boxMaHoaDon_CTHD.getSelectedItem().toString()))
                                 k=true;*/
                if (new ChiTietHoaDonDAO().fixChiTietHoaDon(s)){
                    //if (k)  JOptionPane.showMessageDialog(null,"Fix Faild! The same MaHoaDon");else
                    //{
                    JOptionPane.showMessageDialog(null,"Fix Succsess!");
                    list1.add(s);
                   // }
                }   
                else JOptionPane.showMessageDialog(rootPane, "Fix Faild!");
            } catch (Exception e) {
                e.printStackTrace();
            }
            clearTableCTHD();
           list1 = new ChiTietHoaDonDAO().getlistChiTietHoaDon();
            showTableCTHD();                                       
    }//GEN-LAST:event_btnSua_ChiTietHoaDonActionPerformed

    private void btnThem_ChiTietHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem_ChiTietHoaDonActionPerformed
            ChiTietHoaDon s=new ChiTietHoaDon();
            MatHang ss= new MatHang();
            boolean k=false;
            Integer x=Integer.parseInt(txSoLuong.getText());
            String MaMatHang1=boxMaMatHang_CTHD.getSelectedItem().toString();
            int soluong=0;
            try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/banhang","root","");
            String sql="select SoLuong from mathang where MaMatHang="+"'"+MaMatHang1+"'";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
           
            while (rs.next()) {
                      int xxx=rs.getInt("SoLuong");  
                      soluong=xxx;
            } 
         
            }
            catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
            ss.setSoLuong(soluong-x);
            ss.setMaMatHang(MaMatHang1);
            if (new updateDAO().updateMatHang(ss)) {
                System.out.println("asd");
            } 
                s.setMaHoaDon(boxMaHoaDon_CTHD.getSelectedItem().toString());
                s.setMaMatHang(boxMaMatHang_CTHD.getSelectedItem().toString());
                s.setSoluong(txSoLuong.getText());
                s.setThanhTien(Integer.parseInt(txThanhTien.getText()));
                s.setDonGia(Integer.parseInt(txDonGia.getText()));
                Object[] row= new Object[7];
                s.setTienGiamGia(Integer.parseInt(txTienGiamGia.getText()));
                 for (int i=0;i<list1.size();i++)
                            if (list1.get(i).getMaHoaDon().equals(boxMaHoaDon_CTHD.getSelectedItem().toString()))
                                 k=true;
                 if (new ChiTietHoaDonDAO().addChiTietHoaDon(s)){
                    if (k)  JOptionPane.showMessageDialog(null,"Add Succsess!");else
                    {
                    JOptionPane.showMessageDialog(null,"Add Succsess!");
                    list1.add(s);
                    }
                }   
                else JOptionPane.showMessageDialog(rootPane, "Add Faild!");
            
            clearTableCTHD();
            list1= new ChiTietHoaDonDAO().getlistChiTietHoaDon();
            //showTableCTHD();
    }//GEN-LAST:event_btnThem_ChiTietHoaDonActionPerformed

        
    private void boxMaHoaDon_CTHDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_boxMaHoaDon_CTHDItemStateChanged

    }//GEN-LAST:event_boxMaHoaDon_CTHDItemStateChanged

    private void txTienGiamGiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txTienGiamGiaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txTienGiamGiaKeyPressed

    private void txTienGiamGiaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txTienGiamGiaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txTienGiamGiaKeyReleased

    private void txDonGiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txDonGiaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txDonGiaKeyPressed

    private void txDonGiaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txDonGiaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txDonGiaKeyReleased

    private void tblHoaDon_HoaDonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblHoaDon_HoaDonKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tblHoaDon_HoaDonKeyReleased

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        
        SimpleDateFormat sdf=new  SimpleDateFormat("yyyy-MM-dd"); 
        String date1=sdf.format(date1NgayLapHD.getDate());
        String date2=sdf.format(date2NgayLapHD.getDate());
        model.setRowCount(0);
        Object[] row= new Object[7];
              
        for (int i=0;i<list.size();i++)
            if (list.get(i).getNgayLapHD().equals(date1)||list.get(i).getNgayLapHD().equals(date2))
            {
                row[0]=i+1;
                row[1]=list.get(i).getMaHoaDon();
                row[2]=list.get(i).getMaNV();
                row[3]=list.get(i).getMaChuongTrinh();
                row[4]=list.get(i).getMaKH();
                row[5]=list.get(i).getNgayLapHD();
                row[6]=list.get(i).getGhiChu();
                model.addRow(row);
            }              
    }//GEN-LAST:event_btnSearchActionPerformed
    public void showDB(){
        int selectrow=tblHoaDon_HoaDon.getSelectedRow();     
        
        txMaHoaDon.setText(tblHoaDon_HoaDon.getValueAt(selectrow,1).toString());
        boxMaNV.setSelectedItem(tblHoaDon_HoaDon.getValueAt(selectrow,2).toString());
        boxMaChuongTrinh.setSelectedItem(tblHoaDon_HoaDon.getValueAt(selectrow,3).toString());
        boxMaKhachHang.setSelectedItem(tblHoaDon_HoaDon.getValueAt(selectrow,4).toString());
        Date date;
        try {
            date = new  SimpleDateFormat("yyyy-MM-dd").parse((String)model.getValueAt(selectrow,5));
            dateNgayLapHD.setDate(date);
        } catch (ParseException ex) {
            Logger.getLogger(HoaDon_form.class.getName()).log(Level.SEVERE, null, ex);
        }
        txGhiChu.setText(tblHoaDon_HoaDon.getValueAt(selectrow,6).toString());
    }
    public void showDB1(){
        int selectrow=tblCTHoaDon_ChiTietHoaDon.getSelectedRow();     
        boxMaHoaDon_CTHD.setSelectedItem(tblCTHoaDon_ChiTietHoaDon.getValueAt(selectrow,1).toString());
        boxMaMatHang_CTHD.setSelectedItem(tblCTHoaDon_ChiTietHoaDon.getValueAt(selectrow,2).toString());
        txSoLuong.setText(tblCTHoaDon_ChiTietHoaDon.getValueAt(selectrow,3).toString());
        txThanhTien.setText(tblCTHoaDon_ChiTietHoaDon.getValueAt(selectrow,4).toString());
        txDonGia.setText(tblCTHoaDon_ChiTietHoaDon.getValueAt(selectrow,5).toString());
        txTienGiamGia.setText(tblCTHoaDon_ChiTietHoaDon.getValueAt(selectrow,6).toString());
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        clearTable();
        list = new HoaDonDAO().getListHoadon();
        showTable();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnReset_ChiTietHoaDon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReset_ChiTietHoaDon1ActionPerformed
        // TODO add your handling code here:
        clearTableCTHD();
        list1 = new ChiTietHoaDonDAO().getlistChiTietHoaDon();
        showTableCTHD();
    }//GEN-LAST:event_btnReset_ChiTietHoaDon1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoaDon_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoaDon_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoaDon_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoaDon_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HoaDon_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxMaChuongTrinh;
    private javax.swing.JComboBox<String> boxMaHoaDon_CTHD;
    private javax.swing.JComboBox<String> boxMaKhachHang;
    private javax.swing.JComboBox<String> boxMaMatHang_CTHD;
    private javax.swing.JComboBox<String> boxMaNV;
    private javax.swing.JButton btnReset_ChiTietHoaDon1;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSua_ChiTietHoaDon;
    private javax.swing.JButton btnSua_HoaDon;
    private javax.swing.JButton btnThem_ChiTietHoaDon;
    private javax.swing.JButton btnThem_HoaDon;
    private javax.swing.JButton btnXoa_HoaDon;
    private javax.swing.JButton btnXuat;
    private com.toedter.calendar.JDateChooser date1NgayLapHD;
    private com.toedter.calendar.JDateChooser date2NgayLapHD;
    private com.toedter.calendar.JDateChooser dateNgayLapHD;
    private javax.swing.JPanel dateNgayLapHD1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JLabel lblMaHoaDon;
    private javax.swing.JLabel lblMaHoaDon1;
    private javax.swing.JLabel lblMaHoaDon_HoaDon;
    public javax.swing.JLabel lblNgayLap;
    private javax.swing.JLabel lblSoLuong_CTPM;
    private javax.swing.JLabel lblTongTien_HoaDon;
    private javax.swing.JTable tblCTHoaDon_ChiTietHoaDon;
    private javax.swing.JTable tblHoaDon_HoaDon;
    private javax.swing.JTextField txDonGia;
    private javax.swing.JTextArea txGhiChu;
    private javax.swing.JTextField txMaHoaDon;
    private javax.swing.JTextField txSoLuong;
    private javax.swing.JTextField txThanhTien;
    private javax.swing.JTextField txTienGiamGia;
    // End of variables declaration//GEN-END:variables

    
}
