/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import controller.NhanVienDAO;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.NhanVien;

public class NhanVien_Form extends javax.swing.JFrame {

    private ArrayList<NhanVien> ListNhanVien;
    DefaultTableModel model;

    /**
     * Creates new form frmNhanVien
     */
    public NhanVien_Form() {
        initComponents();
        tbl_nhanvien.setShowGrid(true);
        this.setLocationRelativeTo(null);
        model = new DefaultTableModel();
        model.setColumnIdentifiers(new Object[]{
            "MaNV", "TênNV", "ĐịaChỉNV", "NgaySinh", "Mức Lương", "Ngày Vào Làm", "SDT", "Giới Tính", "CMND"
        });
        tbl_nhanvien.setModel(model);
        tbl_nhanvien.getColumnModel().getColumn(0).setPreferredWidth(40);
        tbl_nhanvien.getColumnModel().getColumn(1).setPreferredWidth(110);
        tbl_nhanvien.getColumnModel().getColumn(2).setPreferredWidth(180);
        tbl_nhanvien.getColumnModel().getColumn(7).setPreferredWidth(50);
        tbl_nhanvien.getColumnModel().getColumn(8).setPreferredWidth(100);
        reloadNhanvien();
    }

    public void reloadNhanvien() {
        ListNhanVien = new NhanVienDAO().getListNhanVien();
        model.setRowCount(0);
        for (NhanVien s : ListNhanVien) {
            model.addRow(new Object[]{
                s.getMaNV(), s.getTenNV(), s.getDiaChiNV(), s.getNgaySinh(), s.getMucLuong(), s.getNgayVaoLam(), s.getSDT(), s.getGioiTinh(), s.getCMND()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_mucluong = new javax.swing.JTextField();
        txt_diachi = new javax.swing.JTextField();
        txt_tennv = new javax.swing.JTextField();
        txt_manv = new javax.swing.JTextField();
        txt_sdt = new javax.swing.JTextField();
        txt_cmnd = new javax.swing.JTextField();
        date_ngaysinh = new com.toedter.calendar.JDateChooser();
        date_vaolam = new com.toedter.calendar.JDateChooser();
        bt_them = new javax.swing.JButton();
        bt_xoa = new javax.swing.JButton();
        bt_sua = new javax.swing.JButton();
        bt_reset = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cb_timkiem = new javax.swing.JComboBox<>();
        txt_ma = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        BT_timkiem = new javax.swing.JButton();
        Cb_ngayvaolam = new javax.swing.JCheckBox();
        Date_timkiem = new com.toedter.calendar.JDateChooser();
        date_vaolam2 = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        bt_reload = new javax.swing.JButton();
        rb_nam = new javax.swing.JRadioButton();
        rb_nu = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_nhanvien = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel14.setText("jLabel14");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaige/icons8-staff-80.png"))); // NOI18N
        jLabel1.setText("Nhân Viên");

        jLabel2.setText("Nhập Mã Nhân Viên:");

        jLabel3.setText("Nhập Tên Nhân Viên:");

        jLabel4.setText("Nhập Địa Chỉ:");

        jLabel5.setText("Nhập Ngày Sinh:");

        jLabel6.setText("Nhập Mức Lương:");

        jLabel7.setText("Nhập Ngày Vào Làm:");

        jLabel8.setText("Nhập Số Điện Thoại:");

        jLabel9.setText("Giới Tính:");

        jLabel10.setText("Nhập CMND:");

        txt_diachi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_diachiActionPerformed(evt);
            }
        });

        txt_manv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_manvActionPerformed(evt);
            }
        });

        bt_them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaige/icons8-add-24.png"))); // NOI18N
        bt_them.setText("Thêm");
        bt_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_themActionPerformed(evt);
            }
        });

        bt_xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaige/icons8-delete-bin-24.png"))); // NOI18N
        bt_xoa.setText("Xóa");
        bt_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_xoaActionPerformed(evt);
            }
        });

        bt_sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaige/icons8-support-26.png"))); // NOI18N
        bt_sua.setText("Sửa");
        bt_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_suaActionPerformed(evt);
            }
        });

        bt_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaige/icons8-reset-24.png"))); // NOI18N
        bt_reset.setText("Reset");
        bt_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_resetActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("Tìm Kiếm");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setText("Tìm theo:");

        cb_timkiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã Nhân Viên", "Tên Nhân Viên", "CMND", "Số Điện Thoại" }));
        cb_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_timkiemActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel13.setText("Nhập:");

        BT_timkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaige/icons8-google-web-search-24.png"))); // NOI18N
        BT_timkiem.setText("Tìm");
        BT_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_timkiemActionPerformed(evt);
            }
        });

        Cb_ngayvaolam.setText("Ngày Vào Làm");

        Date_timkiem.setDateFormatString("yyyy-MM-dd");

        date_vaolam2.setDateFormatString("yyyy-MM-dd");

        jLabel15.setText("Từ:");

        jLabel16.setText("Đến:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(Cb_ngayvaolam)
                                .addGap(22, 22, 22))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Date_timkiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(date_vaolam2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(BT_timkiem))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_ma)
                                    .addComponent(cb_timkiem, 0, 157, Short.MAX_VALUE)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(jLabel11)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_ma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(Cb_ngayvaolam)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Date_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date_vaolam2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BT_timkiem))))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        bt_reload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaige/icons8-process-26.png"))); // NOI18N
        bt_reload.setText("Reload");
        bt_reload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_reloadActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb_nam);
        rb_nam.setSelected(true);
        rb_nam.setText("Nam");

        buttonGroup1.add(rb_nu);
        rb_nu.setText("Nu");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txt_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_them, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(date_vaolam, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(date_ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_tennv, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_mucluong, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(rb_nam)
                                        .addGap(32, 32, 32)
                                        .addComponent(rb_nu)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(txt_cmnd, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(bt_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_reload)
                                .addGap(48, 48, 48)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_manv, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(txt_manv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_tennv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(date_ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txt_mucluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addGap(12, 12, 12))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date_vaolam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_them)
                        .addComponent(bt_xoa)
                        .addComponent(bt_sua)))
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_reset)
                            .addComponent(bt_reload))
                        .addGap(36, 36, 36))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel9))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rb_nam, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rb_nu, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_cmnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(23, 23, 23))))
        );

        tbl_nhanvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9"
            }
        ));
        tbl_nhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_nhanvienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_nhanvien);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_manvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_manvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_manvActionPerformed

    private void txt_diachiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_diachiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_diachiActionPerformed

    private void tbl_nhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_nhanvienMouseClicked
        // TODO add your handling code here:
        int i = tbl_nhanvien.getSelectedRow();
        String date = tbl_nhanvien.getValueAt(i, 3).toString();
        txt_manv.setText(tbl_nhanvien.getValueAt(i, 0).toString());
        txt_tennv.setText(tbl_nhanvien.getValueAt(i, 1).toString());
        txt_diachi.setText(tbl_nhanvien.getValueAt(i, 2).toString());
        try {
            date_ngaysinh.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(date));
            date_vaolam.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(tbl_nhanvien.getValueAt(i, 5).toString()));
        } catch (ParseException ex) {
            Logger.getLogger(NhanVien_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
        txt_mucluong.setText(tbl_nhanvien.getValueAt(i, 4).toString());
        txt_sdt.setText(tbl_nhanvien.getValueAt(i, 6).toString());

        if (tbl_nhanvien.getValueAt(i, 7).toString().equals("m")) {
            rb_nam.doClick();
        } else {
            rb_nu.doClick();
        }
        txt_cmnd.setText(tbl_nhanvien.getValueAt(i, 8).toString());

    }//GEN-LAST:event_tbl_nhanvienMouseClicked

    private void bt_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_themActionPerformed
        // TODO add your handling code here:
        NhanVien s = new NhanVien();
        s.setMaNV(txt_manv.getText());
        s.setTenNV(txt_tennv.getText());
        s.setDiaChiNV(txt_diachi.getText());
        s.setCMND(txt_cmnd.getText());
        if (rb_nam.isSelected()) {
            s.setGioiTinh("m");
        } else {
            s.setGioiTinh("f");
        }
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String date_ngay = sdf.format(this.date_ngaysinh.getDate());
        String date_ngayvaolam = sdf.format(date_vaolam.getDate());
        try {
            s.setNgaySinh(new SimpleDateFormat("yyyy-MM-dd").parse(date_ngay));
        } catch (ParseException ex) {
            Logger.getLogger(NhanVien_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            s.setNgayVaoLam(new SimpleDateFormat("yyyy-MM-dd").parse(date_ngayvaolam));
        } catch (ParseException ex) {
            Logger.getLogger(NhanVien_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
        s.setMucLuong(Integer.parseInt(txt_mucluong.getText()));
        s.setSDT(txt_sdt.getText());
        if (new NhanVienDAO().addNhanVien(s)) {
            JOptionPane.showMessageDialog(rootPane, "Add Success!");
            ListNhanVien.add(s);
            reloadNhanvien();
        } else {
            JOptionPane.showMessageDialog(rootPane, "ID cannot be duplicated!");
        }
        System.out.println(s.getCMND() + s.getDiaChiNV() + s.getGioiTinh() + s.getNgaySinh());

    }//GEN-LAST:event_bt_themActionPerformed

    private void bt_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_xoaActionPerformed
        // TODO add your handling code here:
        NhanVien s = new NhanVien();
        s.setMaNV(txt_manv.getText());
        if (new NhanVienDAO().xoaNhanVien(s)) {
            JOptionPane.showMessageDialog(rootPane, "Success!");
            reloadNhanvien();
        } else {
            JOptionPane.showMessageDialog(rootPane, "FAIL !");
        }
    }//GEN-LAST:event_bt_xoaActionPerformed

    private void bt_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_suaActionPerformed
        // TODO add your handling code here:
        NhanVien s = new NhanVien();
        s.setMaNV(txt_manv.getText());
        s.setTenNV(txt_tennv.getText());
        s.setDiaChiNV(txt_diachi.getText());
        s.setCMND(txt_cmnd.getText());
        if (rb_nam.isSelected()) {
            s.setGioiTinh("m");
        } else {
            s.setGioiTinh("f");
        }
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String date_ngay = sdf.format(this.date_ngaysinh.getDate());
        String date_ngayvaolam = sdf.format(date_vaolam.getDate());
        try {
            s.setNgaySinh(new SimpleDateFormat("yyyy-MM-dd").parse(date_ngay));
        } catch (ParseException ex) {
            Logger.getLogger(NhanVien_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            s.setNgayVaoLam(new SimpleDateFormat("yyyy-MM-dd").parse(date_ngayvaolam));
        } catch (ParseException ex) {
            Logger.getLogger(NhanVien_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
        s.setMucLuong(Integer.parseInt(txt_mucluong.getText()));
        s.setSDT(txt_sdt.getText());
        if (new NhanVienDAO().suaNhanVien(s)) {
            JOptionPane.showMessageDialog(rootPane, "Success!");
            ListNhanVien.add(s);
            reloadNhanvien();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Fail!");
        }
    }//GEN-LAST:event_bt_suaActionPerformed

    private void bt_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_resetActionPerformed
        // TODO add your handling code here:
        txt_manv.setText("");
        txt_cmnd.setText("");
        txt_diachi.setText("");
        txt_mucluong.setText("");
        txt_sdt.setText("");
        txt_tennv.setText("");
        date_ngaysinh.setDateFormatString("");
        date_vaolam.setDateFormatString("");
        rb_nam.setSelected(rootPaneCheckingEnabled);


    }//GEN-LAST:event_bt_resetActionPerformed

    private void BT_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_timkiemActionPerformed
        // TODO add your handling code here:
     String ma = txt_ma.getText();
        if (txt_ma.getText().equals("")) {
            if (Cb_ngayvaolam.isSelected()) {
                model.setRowCount(0);

                for (NhanVien s : ListNhanVien) {
                    if (timkiemNgay(s)) {

                        model.addRow(new Object[]{
                            s.getMaNV(), s.getTenNV(), s.getDiaChiNV(), s.getNgaySinh(), s.getMucLuong(), s.getNgayVaoLam(), s.getSDT(), s.getGioiTinh(), s.getCMND()
                        });
                    }
                }
            }
        } else {
            if ("Mã Nhân Viên" == cb_timkiem.getSelectedItem()) {
                model.setRowCount(0);
                if (Cb_ngayvaolam.isSelected()) {
                    for (NhanVien s : ListNhanVien) {
                        if (timkiemNgay(s)) {
                            if (ma.equals(s.getMaNV())) {
                                model.addRow(new Object[]{
                                    s.getMaNV(), s.getTenNV(), s.getDiaChiNV(), s.getNgaySinh(), s.getMucLuong(), s.getNgayVaoLam(), s.getSDT(), s.getGioiTinh(), s.getCMND()
                                });
                            }

                        }
                    }

                } else {
                    for (NhanVien s : ListNhanVien) {
                        if (ma.equals(s.getMaNV())) {
                            model.addRow(new Object[]{
                                s.getMaNV(), s.getTenNV(), s.getDiaChiNV(), s.getNgaySinh(), s.getMucLuong(), s.getNgayVaoLam(), s.getSDT(), s.getGioiTinh(), s.getCMND()
                            });
                        }
                    }
                }

            }
            if ("Tên Nhân Viên" == cb_timkiem.getSelectedItem()) {
                model.setRowCount(0);
                if (Cb_ngayvaolam.isSelected()) {
                    for (NhanVien s : ListNhanVien) {
                        if (timkiemNgay(s)) {
                            if (ma.equals(s.getTenNV())) {
                                model.addRow(new Object[]{
                                    s.getMaNV(), s.getTenNV(), s.getDiaChiNV(), s.getNgaySinh(), s.getMucLuong(), s.getNgayVaoLam(), s.getSDT(), s.getGioiTinh(), s.getCMND()
                                });
                            }

                        }
                    }

                } else {
                    for (NhanVien s : ListNhanVien) {
                        if (ma.equals(s.getTenNV())) {
                            model.addRow(new Object[]{
                                s.getMaNV(), s.getTenNV(), s.getDiaChiNV(), s.getNgaySinh(), s.getMucLuong(), s.getNgayVaoLam(), s.getSDT(), s.getGioiTinh(), s.getCMND()
                            });
                        }
                    }
                }

            }
            if ("CMND" == cb_timkiem.getSelectedItem()) {
                model.setRowCount(0);
                if (Cb_ngayvaolam.isSelected()) {
                    for (NhanVien s : ListNhanVien) {
                        if (timkiemNgay(s)) {
                            if (ma.equals(s.getCMND())) {
                                model.addRow(new Object[]{
                                    s.getMaNV(), s.getTenNV(), s.getDiaChiNV(), s.getNgaySinh(), s.getMucLuong(), s.getNgayVaoLam(), s.getSDT(), s.getGioiTinh(), s.getCMND()
                                });
                            }

                        }
                    }

                } else {
                    for (NhanVien s : ListNhanVien) {
                        if (ma.equals(s.getCMND())) {
                            model.addRow(new Object[]{
                                s.getMaNV(), s.getTenNV(), s.getDiaChiNV(), s.getNgaySinh(), s.getMucLuong(), s.getNgayVaoLam(), s.getSDT(), s.getGioiTinh(), s.getCMND()
                            });
                        }
                    }
                }

            }
            if ("sỐ Điện Thoại" == cb_timkiem.getSelectedItem()) {
                model.setRowCount(0);
                if (Cb_ngayvaolam.isSelected()) {
                    for (NhanVien s : ListNhanVien) {
                        if (timkiemNgay(s)) {
                            if (ma.equals(s.getSDT())) {
                                model.addRow(new Object[]{
                                    s.getMaNV(), s.getTenNV(), s.getDiaChiNV(), s.getNgaySinh(), s.getMucLuong(), s.getNgayVaoLam(), s.getSDT(), s.getGioiTinh(), s.getCMND()
                                });
                            }

                        }
                    }

                } else {
                    for (NhanVien s : ListNhanVien) {
                        if (ma.equals(s.getSDT())) {
                            model.addRow(new Object[]{
                                s.getMaNV(), s.getTenNV(), s.getDiaChiNV(), s.getNgaySinh(), s.getMucLuong(), s.getNgayVaoLam(), s.getSDT(), s.getGioiTinh(), s.getCMND()
                            });
                        }
                    }
                }

            }

        }
    }//GEN-LAST:event_BT_timkiemActionPerformed

    private void bt_reloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_reloadActionPerformed
        // TODO add your handling code here:
        reloadNhanvien();
    }//GEN-LAST:event_bt_reloadActionPerformed

    private void cb_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_timkiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_timkiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhanVien_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhanVien_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhanVien_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhanVien_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhanVien_Form().setVisible(true);
            }
        });
    }

    public boolean timkiemNgay(NhanVien s) {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String date_timkiem = sdf.format(Date_timkiem.getDate());
        String date = sdf.format(s.getNgayVaoLam());
        if (date.compareTo(date_timkiem) == 0) {
            return true;
        }
        return false;
    }

    public boolean kiemtraNgay() {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String date1 = sdf.format(Date_timkiem.getDate());
        if (date1 == null) {
            System.out.println(date1);
            return false;
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_timkiem;
    private javax.swing.JCheckBox Cb_ngayvaolam;
    private com.toedter.calendar.JDateChooser Date_timkiem;
    private javax.swing.JButton bt_reload;
    private javax.swing.JButton bt_reset;
    private javax.swing.JButton bt_sua;
    private javax.swing.JButton bt_them;
    private javax.swing.JButton bt_xoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cb_timkiem;
    private com.toedter.calendar.JDateChooser date_ngaysinh;
    private com.toedter.calendar.JDateChooser date_vaolam;
    private com.toedter.calendar.JDateChooser date_vaolam2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rb_nam;
    private javax.swing.JRadioButton rb_nu;
    private javax.swing.JTable tbl_nhanvien;
    private javax.swing.JTextField txt_cmnd;
    private javax.swing.JTextField txt_diachi;
    private javax.swing.JTextField txt_ma;
    private javax.swing.JTextField txt_manv;
    private javax.swing.JTextField txt_mucluong;
    private javax.swing.JTextField txt_sdt;
    private javax.swing.JTextField txt_tennv;
    // End of variables declaration//GEN-END:variables
}
